### ISSUE TITLE
Analytics and Alerts don't work locally

### ISSUE THREAD

**Issue by irisuk** [PredixDev/px-sample-app#1]
When running this application locally, the dashboard page works.However, the analytics or the alerts don't appear when clicking the associated button in the navigation bar at the top. However, when I push it to the cloud everything works fine.

**Comment by randyaskin** [comment]
That's strange, I've never seen that issue before. I'm not doing anything fancy with app-route or anything, just swapping out the conditional areas of the page based on the selection in app-nav. What are you using for serving it locally? `gulp serve` or something else? Can you try inspecting the `<px-sample-app>` tag and verifying that the `selected` property is getting changed when you click another option?

**Comment by irisuk** [comment]
Sure I will check the tag and let you know.  I am using gulp serve.  on starting the instance the address is http://localhost:8080 so am not sure if that could be the issue.

**Comment by irisuk** [comment]
One thing to add is that I am using the Predix development machine to run this app.

**Comment by irisuk** [comment]
OK, I have it working now. :)
When running firefox as sudo this works fine and the navigation works locally.  There must be a permissions issue with the predix dev VM.  Would be nice if anyone else is experiencing any issues like this.

**Comment by randyaskin** [comment]
Glad you were able to get up and running. If you wouldn't mind summarizing the issue on forum.predix.io, someone from the DevBox team may be able to help you via that channel.
